[package]
name = "tetra_test"
version = "0.1.0"
authors = ["Eiyeron Fulmincendii <eiyeron@retroactive.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.6"
